"""
Django settings for sync project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from os import environ
from sync.sync import enable_autosync
from typing import Dict, Any, List
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEV: bool = environ.get("DEV", "false").lower() == "true"
DEBUG = DEV

ALLOWED_HOSTS = [
    f".{environ["MAIN_DOMAIN"]}",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "sync.auth.AuthMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# START - CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [environ["MAIN_URL"]]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
# END - CORS

# START - CSRF & SESSION cookies
# CORS & CSRF depend on whether or not it's a dev server
CSRF_TRUSTED_ORIGINS = [environ["MAIN_URL"]]
CSRF_COOKIE_SAMESITE = "Strict" if DEV else "None"
CSRF_COOKIE_SECURE = False if DEV else True
CSRF_COOKIE_HTTPONLY = False if DEV else True
CSRF_USE_SESSIONS = False
CSRF_COOKIE_PARTITIONED = False if DEV else True
CSRF_COOKIE_DOMAIN = environ["CACHE_DOMAIN"]

SESSION_COOKIE_SAMESITE = "Strict" if DEV else "None"
SESSION_COOKIE_SECURE = False if DEV else True
SESSION_COOKIE_HTTPONLY = False if DEV else True
SESSION_COOKIE_PARTITIONED = False if DEV else True
SESSION_COOKIE_DOMAIN = environ["CACHE_DOMAIN"]

ROOT_URLCONF = "sync.urls"

TEMPLATES: List[Dict[str, Any]] = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sync.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES: Dict[str, Any] = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "wywywebsite",
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "password"),
        "HOST": environ.get("DATABASE_HOST", "postgres"),
        "PORT": os.environ.get("POSTGRES_PORT", "5433"),
        "OPTIONS": {
            "connect_timeout": 5,
        },
    },
    "info": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "info",
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "password"),
        "HOST": "wywywebsite-cache_database",
        "PORT": os.environ.get("POSTGRES_PORT", "5433"),
        "OPTIONS": {
            "connect_timeout": 5,
        },
    },
}

LOGGING: Dict[str, Any] = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
        "sync": {
            "level": os.getenv("SYNC_LOG_LEVEL", "INFO"),
            "class": "logging.FileHandler",
            "filename": "/var/log/Wywy-Website/cache/sync.log",
            "formatter": "simple",
        },
        "sync-debug": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "/var/log/Wywy-Website/cache/sync-debug.log",
            "formatter": "verbose",
        },
        "cache": {
            "level": os.getenv("CACHE_LOG_LEVEL", "WARNING"),
            "class": "logging.FileHandler",
            "filename": "/var/log/Wywy-Website/cache/cache.log",
            "formatter": "simple",
        },
        "cache-debug": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "/var/log/Wywy-Website/cache/cache-debug.log",
            "formatter": "verbose",
        },
        "schema": {
            "level": os.getenv("SCHEMA_LOG_LEVEL", "WARNING"),
            "class": "logging.FileHandler",
            "filename": "/var/log/Wywy-Website/cache/schema.log",
            "formatter": "simple",
        },
        "schema-debug": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "/var/log/Wywy-Website/cache/schema-debug.log",
            "formatter": "verbose",
        },
        "database": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": "/var/log/Wywy-Website/cache/database.log",
            "formatter": "simple",
        },
        "database-debug": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "/var/log/Wywy-Website/cache/database-debug.log",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "sync": {
            "handlers": ["sync", "sync-debug"],
            "level": "DEBUG",
            "propagate": True,
        },
        "cache": {
            "handlers": ["cache", "cache-debug"],
            "level": "DEBUG",
            "propagate": True,
        },
        "schema": {
            "handlers": ["schema", "schema-debug"],
            "level": "DEBUG",
            "propagate": True,
        },
        "database": {
            "handlers": ["database", "database-debug"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# enable auto-sync
enable_autosync()


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
