name: cache

services:
  create_tables:
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/cache/.env.dev
        required: true
    develop:
      watch:
        - action: sync+restart
          path: ./../apps/create_tables
          target: ./apps/create_tables
          initial_sync: true

  sync:
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/cache/.env.dev
        required: true
    environment:
      - DEV=TRUE
    networks:
      - wywy_website_master_database-sql_receptionist
      - default

  # @TODO secrets for db authentication
  database:
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/cache/.env.dev
        required: true

networks:
  default: {}
  wywy_website_master_database-sql_receptionist:
    external: true
    name: wywy_website_master_database-sql_receptionist
