name: cache

services:
  cloudflared:
    working_dir: /apps/cloudflared
    build:
      context: ../
      dockerfile: apps/cloudflared/Dockerfile
    environment:
      TZ: America/Toronto
      TUNNEL_TOKEN_FILE: /run/secrets/wywywebsite-cache-cloudflared-cloudflare
    entrypoint: /entrypoint.sh
    restart: unless-stopped
    secrets:
      - wywywebsite-cache-cloudflared-cloudflare
    networks:
      - cloudflared

  sync:
    environment:
      - DEV=FALSE
    command: gunicorn sync.wsgi --bind 0.0.0.0:${SYNC_PORT}

  # @TODO secrets for db authentication

secrets:
  wywywebsite-cache-cloudflared-cloudflare:
    file: ${SECRETS_DIR}/cache/cloudflared-cloudflare-token.txt

networks:
  cloudflared:
    name: cloudflared
